# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_nastanka', models.DateTimeField(verbose_name='datum nastanka')),
                ('naslov', models.TextField()),
                ('vsebina', models.TextField()),
                ('sporocilo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UporabnikProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika_profila', models.ImageField(blank=True, default='profili/user-default.png', upload_to='profili')),
                ('uporabnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='stran',
            name='avtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UporabnikProfil'),
        ),
    ]
