# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160115_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stran',
            name='naslov',
            field=models.CharField(max_length=200),
        ),
    ]
