# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160115_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stran',
            name='datum_nastanka',
            field=models.DateTimeField(null='True', verbose_name='datum nastanka'),
        ),
    ]
