# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160116_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stran',
            name='avtor',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='myapp.UporabnikProfil'),
        ),
    ]
